### ISSUE TITLE
WorkerService run returns an incorrect object

### ISSUE THREAD

**Issue by sviatoslav-lebediev** [madeindjs/nestjs-graphile-worker#15]
It seems that in the `WorkerService run` method, `runner.promise` is returned instead of returning a `runner`. As a result, it is not possible to stop the runner manually.  I can create a PR, but the question is, do I need to create a separate method, or is it okay to change an interface and return a `runner` instead of `void`?

https://github.com/madeindjs/nestjs-graphile-worker/blob/e94ce7fde597dde64ebd0363dececa62e8735e93/src/services/worker.service.ts#L41

**Comment by madeindjs** [comment]
Thanks for the report, I think it's fine to return the runner instead of nothing. You can create a PR and increment the minor version, I will accept it and merge it 😉

**Comment by sviatoslav-lebediev** [comment]
The PR is here https://github.com/madeindjs/nestjs-graphile-worker/pull/16 , if everything is ok please release it when you have time. Thank you

**Comment by madeindjs** [comment]
@sviatoslav-lebediev I merged you PR and [it's on NPM now](https://www.npmjs.com/package/nestjs-graphile-worker/v/0.5.0). Thank you

**Comment by sviatoslav-lebediev** [comment]
thank you
