### ISSUE TITLE
Update of the dependency to graphile-worker

### ISSUE THREAD

**Issue by gco-lapala** [madeindjs/nestjs-graphile-worker#17]
Hello everyone, and thank you for this library.

Would it be possible to have a version compatible with the latest version of graphile-worker, currently at v0.16.5?

**Comment by madeindjs** [comment]
Helllo @gco-lapala , I just increased the `peerDependencies` for `graphile-worker` (https://github.com/madeindjs/nestjs-graphile-worker/commit/a4cfad89c41c11a15d4e6d809d27fcdc579acc52) and publish it as [`v0.6.0`](https://www.npmjs.com/package/nestjs-graphile-worker/v/0.6.0)

Please note I just ran unit tests to check if it works, feel free to open an issue if you see a breaking change.
