### ISSUE TITLE
Do this integration supports Recurring tasks (crontab)?

### ISSUE THREAD

**Issue by aguirrel** [madeindjs/nestjs-graphile-worker#25]
Hi guys,

I'm trying to schedule some recurring tasks for my project. It seems that [graphile does support](https://worker.graphile.org/docs/cron) it but I can't find how could I integrate it using nestjs and nesstjs-graphile-worker package.

Could you guide me?

Thanks!

**Comment by madeindjs** [comment]
Hello @aguirrel ,

The crontab can be given in library mode using [`RunnerOption`](https://github.com/graphile/worker/blob/7feecdde5692569f006d3379f4caee01c4482707/src/interfaces.ts#L727-L731). We're using the runner option in the module configuration, so you should be able to do something like this

```ts
@Module({
  imports: [
    ConfigModule.forRoot(),
    GraphileWorkerModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (config: ConfigService) => ({
        connectionString: config.get('PG_CONNECTION'),
        // see syntax at https://worker.graphile.org/docs/cron#crontab-format
        crontab: [
          ' * * * * * taskIdentifier ?priority=1 {"foo": "bar"}',
        ].join('\n')
      }),
    }),
  ],
  controllers: [AppController],
  providers: [AppService, HelloTask],
})
export class AppModule {}
``` 

I never tested it though, I will be happy to have your feedback about it.

---

Alternatively, a simple solution is to rely on [`@nestjs/schedule`](https://docs.nestjs.com/techniques/task-scheduling) instead. Something like

```ts
import { Injectable, Logger } from "@nestjs/common";
import { Cron } from "@nestjs/schedule";
import { WorkerService } from "nestjs-graphile-worker";

@Injectable()
export class TasksService {
  private readonly logger = new Logger(TasksService.name);

  constructor(private readonly graphileWorker: WorkerService) {}

  @Cron("45 * * * * *")
  async handleCron() {
    // create a job each hour at 45'
    await this.graphileWorker.addJob("hello", { hello: "world" });
    this.logger.debug("Called when the current second is 45");
  }
}
```
The drawback is, it's not a good solution when your service is replicated. You should use Graphile's CRON if so.

**Comment by aguirrel** [comment]
Hi @madeindjs ,

Using crontab inside the factory worked like a charm.

Thanks a lot!
